### ISSUE TITLE
Switch to @faker-js/faker

### ISSUE THREAD

**Issue by mmirus** [bbbco/insomnia-plugin-faker#11]
Hi there! @faker-js/faker is probably what you want to use for this now. The original library was turned into malware and has since been taken offline.

Links:
- https://fakerjs.dev/about/announcements/2022-01-14.html
- https://github.com/faker-js/faker

**Comment by dstockhammer** [comment]
Hi @bbbco! First of all, thanks for creating this plugin! Do you have any plans to work on this any time soon? If not, would you consider accepting a contribution to this effect? I'm not overly familiar with how faker evolved since the release included in this library, but judging from a quick glance at https://fakerjs.dev it looks like everything is still there + some very useful additions.

**Comment by bbbco** [comment]
Hi Daniel,

I actually do have a bit of work I've done to update the library. I just
haven't gotten a chance to verify it completely and push it up. Thanks
for the nudge!

Brian Goad
@bbbco
Creative Analytic Convergence

On June 12, 2022, GitHub Notifications ***@***.***> wrote:
> Hi @bbbco <https://github.com/bbbco>! First of all, thanks for
> creating this plugin! Do you have any plans to work on this any time
> soon? If not, would you consider accepting a contribution to this
> effect? I'm not overly familiar with how faker evolved since the
> release included in this library, but judging from a quick glance at
> <https://fakerjs.dev> it looks like everything is still there + some
> very useful additions.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/bbbco/insomnia-plugin-faker/issues/11#issuecomment-
1153243749>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAAHPWE2GJTIZWEE2KIKAJLVOYOPNANCNFSM5TLFY3OQ>.
You are receiving this because you were mentioned.Message ID:
***@***.***>

**Comment by bbbco** [comment]
I just pushed up version 1.1.0 that takes care of this.

**Comment by mmirus** [comment]
Thanks!
