### ISSUE TITLE
Not seeing Faker - Generate Faker data in Insomnia

### ISSUE THREAD

**Issue by jandreaucodes** [bbbco/insomnia-plugin-faker#17]
I've installed the plugin on a new work laptop, but do not see the same options as shown in the Github docs.

![Insomnia-LB9sGjzj-001075](https://github.com/bbbco/insomnia-plugin-faker/assets/12860371/370e630d-6f1b-4932-af36-c79a4c95c72c)

I only see this "generate random outputs" Function for Faker, which seems to be missing some randomizations I'm after (such as State and Postal Code).

I've uninstalled the plugin and reinstalled it. Any tips on what I can look for?

**Comment by jandreaucodes** [comment]
Future, it looks like all of the once-pretty (according to the docs) options for the Function are now gone.

![Insomnia-gwsA9FRF-001077](https://github.com/bbbco/insomnia-plugin-faker/assets/12860371/be4cecb2-f059-442d-9dc5-8b069bb0de7b)

I don't see the option to go to Faker → Address and then specify what type of Address I want, where I used to be able to do that.

**Comment by bbbco** [comment]
Hi @jandreaucodes . Thanks for this report. 

Because of Kong's decision to require users to signin to gain complete functionality of the Insomnia product, I have moved on to another REST client. As a consequence, I am no longer supporting this plugin.

Feel free to fork it and get it working again yourself. I'll plan to mark it as archived.

**Comment by bbbco** [comment]
Hi @jandreaucodes . It looks like you are using a newer version of Insomnia that has the Faker functionality baked in, but in a slightly different way. This plugin is no longer useful and will be archived.
